### PR TITLE
update build script

### PR DESCRIPTION
**Pull request by nicks**
Checklist
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nicks** [comment]
@joseph-zhong here's what i think it should be, but i'm still struggling to test this locally

@conda-forge-admin, please rerender

**Comment by joseph-zhong** [comment]
Thanks for getting to this @nicks! Just to be sure we don't need to re-render, you can check by running the following in the base of the `tilt-feedstock` repo: (https://conda-forge.org/docs/maintainer/updating_pkgs.html#dev-rerender-local)

```bash
conda install -c conda-forge conda-smithy
conda smithy rerender
```

If there are any changes you can just commit them upstream

**Comment by nicks** [comment]
@conda-forge-admin, please rerender

**Comment by nicks** [comment]
oops, i think i need to re-do this from a fork, hold on

**Pull request closed without merging**
